# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
