# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20180521_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='status',
            new_name='available',
        ),
    ]
