# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20180516_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pwd',
            new_name='password',
        ),
    ]
