# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='1939-5-1'),
            preserve_default=False,
        ),
    ]
