# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='website.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='added_by', to='website.User'),
        ),
    ]
