# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='tbd'),
            preserve_default=False,
        ),
    ]
